package com.sodifrance.stage.esb.talend.conditional;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-14T12:19:00.177+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "ArticleConditionalWSImplService", 
                  wsdlLocation = "http://localhost:8085/ArticleConditionalWSImplPort?wsdl",
                  targetNamespace = "http://conditional.talend.esb.stage.sodifrance.com/") 
public class ArticleConditionalWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://conditional.talend.esb.stage.sodifrance.com/", "ArticleConditionalWSImplService");
    public final static QName ArticleConditionalWSImplPort = new QName("http://conditional.talend.esb.stage.sodifrance.com/", "ArticleConditionalWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8085/ArticleConditionalWSImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ArticleConditionalWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8085/ArticleConditionalWSImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ArticleConditionalWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ArticleConditionalWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArticleConditionalWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ArticleConditionalWS
     */
    @WebEndpoint(name = "ArticleConditionalWSImplPort")
    public ArticleConditionalWS getArticleConditionalWSImplPort() {
        return super.getPort(ArticleConditionalWSImplPort, ArticleConditionalWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArticleConditionalWS
     */
    @WebEndpoint(name = "ArticleConditionalWSImplPort")
    public ArticleConditionalWS getArticleConditionalWSImplPort(WebServiceFeature... features) {
        return super.getPort(ArticleConditionalWSImplPort, ArticleConditionalWS.class, features);
    }

}
