package com.sodifrance.referential_book;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T14:34:30.352+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "BookWSImplService", 
                  wsdlLocation = "http://localhost:8080/referential-book-0.0.1-SNAPSHOT/services/1.0.0/CDWSImplPort/?wsdl",
                  targetNamespace = "http://referential_book.sodifrance.com/") 
public class BookWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://referential_book.sodifrance.com/", "BookWSImplService");
    public final static QName BookWSImplPort = new QName("http://referential_book.sodifrance.com/", "BookWSImplPort");
    static {
        URL url = BookWSImplService.class.getResource("bookws.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(BookWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "bookws.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public BookWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public BookWSImplService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public BookWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public BookWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns BookWS
     */
    @WebEndpoint(name = "BookWSImplPort")
    public BookWS getBookWSImplPort() {
        return super.getPort(BookWSImplPort, BookWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookWS
     */
    @WebEndpoint(name = "BookWSImplPort")
    public BookWS getBookWSImplPort(WebServiceFeature... features) {
        return super.getPort(BookWSImplPort, BookWS.class, features);
    }

}
