
package com.sodifrance.referential_book.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.0
 * Mon May 14 15:37:22 CEST 2012
 * Generated source version: 2.6.0
 */

@XmlRootElement(name = "getAllBook", namespace = "http://referential_book.sodifrance.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllBook", namespace = "http://referential_book.sodifrance.com/")

public class GetAllBook {


}

