
package com.sodifrance.referential_cd.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.0
 * Mon May 14 12:06:07 CEST 2012
 * Generated source version: 2.6.0
 */

@XmlRootElement(name = "deleteCDResponse", namespace = "http://referential_cd.sodifrance.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteCDResponse", namespace = "http://referential_cd.sodifrance.com/")

public class DeleteCDResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

