package com.sodifrance.referential_cd.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.0
 * Mon May 14 12:06:07 CEST 2012
 * Generated source version: 2.6.0
 */

@XmlRootElement(name = "getCDResponse", namespace = "http://referential_cd.sodifrance.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCDResponse", namespace = "http://referential_cd.sodifrance.com/")

public class GetCDResponse {

	@XmlElement(name = "return")
    private java.util.List<com.sodifrance.referential_cd.CD> _return;

    public java.util.List<com.sodifrance.referential_cd.CD> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.sodifrance.referential_cd.CD> new_return)  {
        this._return = new_return;
    }
	
}