
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sodifrance.stage.esb.servicemix;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-21T17:45:05.606+02:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "ArticleWSImplService",
                      portName = "ArticleWSImplPort",
                      targetNamespace = "http://servicemix.esb.stage.sodifrance.com/",
                      wsdlLocation = "http://localhost:8085/ArticleWSImplPort?wsdl",
                      endpointInterface = "com.sodifrance.stage.esb.servicemix.ArticleWS")
                      
public class ArticleWSImpl implements ArticleWS {

    private static final Logger LOG = Logger.getLogger(ArticleWSImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sodifrance.stage.esb.servicemix.ArticleWS#getAllArticle(*
     */
    public java.util.List<com.sodifrance.stage.esb.servicemix.Article> getAllArticle() { 
        LOG.info("Executing operation getAllArticle");
        try {
            java.util.List<com.sodifrance.stage.esb.servicemix.Article> _return = new java.util.ArrayList<com.sodifrance.stage.esb.servicemix.Article>();
            com.sodifrance.stage.esb.servicemix.Article _returnVal1 = new com.sodifrance.stage.esb.servicemix.Article();
            _returnVal1.setAuthor("Author-621806629");
            _returnVal1.setKind("Kind568245895");
            _returnVal1.setEditor("Editor270400081");
            _returnVal1.setMeta("Meta-2114689023");
            _returnVal1.setTitle("Title1070320730");
            _returnVal1.setPublishDate("2012-05-21T17:36:03.846+02:00");
            _returnVal1.setReleaseDate("2012-05-21T17:36:03.853+02:00");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
