
package com.sodifrance.referential_book.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.0
 * Mon May 14 15:37:22 CEST 2012
 * Generated source version: 2.6.0
 */

@XmlRootElement(name = "deleteBook", namespace = "http://referential_book.sodifrance.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteBook", namespace = "http://referential_book.sodifrance.com/")

public class DeleteBook {

    @XmlElement(name = "arg0")
    private com.sodifrance.referential_book.Book arg0;

    public com.sodifrance.referential_book.Book getArg0() {
        return this.arg0;
    }

    public void setArg0(com.sodifrance.referential_book.Book newArg0)  {
        this.arg0 = newArg0;
    }

}

