package com.sodifrance.referential_book.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.0
 * Mon May 14 15:37:22 CEST 2012
 * Generated source version: 2.6.0
 */

@XmlRootElement(name = "getBook", namespace = "http://referential_book.sodifrance.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBook", namespace = "http://referential_book.sodifrance.com/",propOrder = {"arg0"})

public class GetBook {
	
	@XmlElement(name = "arg0")
	private java.lang.String arg0;

	public java.lang.String getArg0() {
		return this.arg0;
	}

	public void setArg0(java.lang.String newArg0)  {
		this.arg0 = newArg0;
	}
	
}


