(: 
Generated by Apache ServiceMix Archetype
:)
<getArticleConditionalResponse>{
for $result in all//getArticleConditionalResponse/return
      			return $result			
}</getArticleConditionalResponse>