package com.sodifrance.stage.esb.servicemix;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-14T11:50:17.103+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://servicemix.esb.stage.sodifrance.com/", name = "ArticleWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ArticleWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllArticle", targetNamespace = "http://servicemix.esb.stage.sodifrance.com/", className = "com.sodifrance.stage.esb.servicemix.GetAllArticle")
    @WebMethod(action = "urn:getAllArticle")
    @ResponseWrapper(localName = "getAllArticleResponse", targetNamespace = "http://servicemix.esb.stage.sodifrance.com/", className = "com.sodifrance.stage.esb.servicemix.GetAllArticleResponse")
    public java.util.List<com.sodifrance.stage.esb.servicemix.Article> getAllArticle();
}
