package com.sodifrance.referential_cd;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T14:23:42.451+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "CDWSImplService", 
                  wsdlLocation = "http://localhost:8080/referential-cd-0.0.1-SNAPSHOT/services/1.0.0/CDWSImplPort/?wsdl",
                  targetNamespace = "http://referential_cd.sodifrance.com/") 
public class CDWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://referential_cd.sodifrance.com/", "CDWSImplService");
    public final static QName CDWSImplPort = new QName("http://referential_cd.sodifrance.com/", "CDWSImplPort");
    static {
        URL url = CDWSImplService.class.getResource("cdref.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CDWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "cdws.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CDWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CDWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CDWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public CDWSImplService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public CDWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public CDWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns CDWS
     */
    @WebEndpoint(name = "CDWSImplPort")
    public CDWS getCDWSImplPort() {
        return super.getPort(CDWSImplPort, CDWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CDWS
     */
    @WebEndpoint(name = "CDWSImplPort")
    public CDWS getCDWSImplPort(WebServiceFeature... features) {
        return super.getPort(CDWSImplPort, CDWS.class, features);
    }

}
