package com.sodifrance.referential_cd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.sodifrance.stage.esb.mule.ObjectFactory;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T14:23:42.440+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://referential_cd.sodifrance.com/", name = "CDWS")
@XmlSeeAlso({ObjectFactory.class})
public interface CDWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addCD", targetNamespace = "http://referential_cd.sodifrance.com/", className = "com.sodifrance.referential_cd.AddCD")
    @WebMethod(action = "urn:AddCD")
    @ResponseWrapper(localName = "addCDResponse", targetNamespace = "http://referential_cd.sodifrance.com/", className = "com.sodifrance.referential_cd.AddCDResponse")
    public java.lang.String addCD(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteCD", targetNamespace = "http://referential_cd.sodifrance.com/", className = "com.sodifrance.referential_cd.DeleteCD")
    @WebMethod(action = "urn:deleteCD")
    @ResponseWrapper(localName = "deleteCDResponse", targetNamespace = "http://referential_cd.sodifrance.com/", className = "com.sodifrance.referential_cd.DeleteCDResponse")
    public java.lang.String deleteCD(
        @WebParam(name = "arg0", targetNamespace = "")
       com.sodifrance.referential_cd.Cd arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllCD", targetNamespace = "http://referential_cd.sodifrance.com/", className = "com.sodifrance.referential_cd.GetAllCD")
    @WebMethod(action = "urn:getAllCD")
    @ResponseWrapper(localName = "getAllCDResponse", targetNamespace = "http://referential_cd.sodifrance.com/", className = "com.sodifrance.referential_cd.GetAllCDResponse")
    public java.util.List<com.sodifrance.referential_cd.Cd> getAllCD();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateCD", targetNamespace = "http://referential_cd.sodifrance.com/", className = "com.sodifrance.referential_cd.UpdateCD")
    @WebMethod(action = "urn:updateCD")
    @ResponseWrapper(localName = "updateCDResponse", targetNamespace = "http://referential_cd.sodifrance.com/", className = "com.sodifrance.referential_cd.UpdateCDResponse")
    public java.lang.String updateCD(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sodifrance.referential_cd.Cd arg0
    );
}
